<?php
namespace App\Models\Base;

use App\User;

class UserWorth extends UserModel
{
    protected $table = "users_worth";

    protected $fillable = [
        'total', 'day1','day2','day3','day4','day5','day6','day7','week2','week3','week4',
        'ext_day1','ext_day2','ext_day3','ext_day4','ext_day5','ext_day6','ext_day7','ext_week2','ext_week3','ext_week4'
    ];

    /**
     * 记录用户价值
     * @param $user_id
     * @param $worth
     * @param bool $is_ad
     */
    static public function updateWorth($user_id,$worth,$is_ad=true)
    {
        $record = self::find($user_id);

        $day = time() - $record['register_timestamp'];

        if($day <= 86400 * 7)
        {
            $key = "day".ceil($day / 86400);
            if(!$is_ad)
                $key = "ext_".$key;
        }
        else if($day <= 86400 * 28)
        {
            $key = "week".ceil($day / 86400 / 7);
            if(!$is_ad)
                $key = "ext_".$key;
        }
        $updateArr[$key] = $record[$key] + $worth;
        $updateArr['total'] = $record['total'] + $worth;
        $record->update($updateArr);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //初始化
        $user = User::find($this['id']);
        $this['register_timestamp'] = strtotime($user['created_at']);
        $this['total'] = 0;
    }
}
